services:
  web:
    image: nginx:stable-alpine
    container_name: web
    ports:
      - "8082:80"
    networks:
      - app_network
    volumes:
      - ./web:/usr/share/nginx/html
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: db_mypassword
      MYSQL_DATABASE: web_db
    networks:
      - app_network
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - db

  jenkins:
    build: ./jenkins
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  
    networks:
      - app_network
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    user: root 
    depends_on:
      - db
      - backend

networks:
  app_network:
    driver: bridge

volumes:
  jenkins-data:
