services:
  web:
    image: nginx:stable-alpine
    container_name: web
    networks:
      - app_network
    volumes:
      - ./web:/usr/share/nginx/html
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: db_mypassword
      MYSQL_DATABASE: web_db
    networks:
      - app_network
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: backend
    networks:
      - app_network
    depends_on:
      - db
    command: ["npm", "test"] 

networks:
  app_network:
    driver: bridge
